# Basic
title: vergil wang
subtitle: 
welcome_message: iOS Developer
description: Hi, i'm vergilw, i'm a iOS developer from China, i'm living in Hubei,Wuhan.
creator: <a href="https://github.com/vergilw">@vergilw</a>

url: "https://vergilw.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/vergilw'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: vergilw
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: antjun@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
